apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-example-app-pdb
  namespace: test-app
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: example-app # <-- Not pointed at our Deployment
